# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('foto', models.ImageField(upload_to='tienda/productos')),
                ('precio', models.IntegerField()),
                ('abierto_desde_las', models.TimeField()),
                ('cierra_a_las', models.TimeField()),
            ],
        ),
    ]
