# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField()),
                ('hora', models.TimeField()),
            ],
        ),
    ]
