# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 18:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_remove_visita_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='cuenta',
        ),
        migrations.AlterField(
            model_name='visita',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 30, 13, 1, 42, 903791)),
        ),
    ]
