# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 23:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_auto_20171130_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='para_hombre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='para_mujer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='para_niños',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visita',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 1, 18, 39, 33, 9276)),
        ),
    ]
