# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 21:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_auto_20171201_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='visita',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 2, 16, 20, 3, 810480)),
        ),
    ]
