# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 23:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_auto_20171204_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripción',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chico',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 12, 18, 53, 31, 888394)),
        ),
        migrations.AlterField(
            model_name='dama',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 12, 18, 53, 31, 888394)),
        ),
        migrations.AlterField(
            model_name='hombre',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 12, 18, 53, 31, 888394)),
        ),
        migrations.AlterField(
            model_name='visita',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 12, 18, 53, 31, 888394)),
        ),
    ]
