# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 22:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_auto_20171215_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descripción',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='para_niños',
            new_name='para_chicos',
        ),
        migrations.AlterField(
            model_name='chico',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 15, 17, 0, 14, 820316)),
        ),
        migrations.AlterField(
            model_name='dama',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 15, 17, 0, 14, 820316)),
        ),
        migrations.AlterField(
            model_name='hombre',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 15, 17, 0, 14, 820316)),
        ),
        migrations.AlterField(
            model_name='visita',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 15, 17, 0, 14, 820316)),
        ),
    ]
