# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_costumer'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='abierto_desde_las',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='costumer',
            name='cierra_a_las',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='costumer',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
