# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171123_0135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Costumer',
        ),
    ]
